title: Knowledge Repo EU
author: Javier Martínez
email: javier.martinez@cabify.com
description: > # this means to ignore newlines until "baseurl:"
  Here is my awesome new site description. I can edit this
  line in _config.yml if I want. It will appear in my document head meta (for
  Google search results) and in my feed.xml site description. ¿Isnt it great :D?

# social links
twitter_username: @githubfreak
github_username:  Github freak

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima.
